WebPortal/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebPortal.Models;

namespace WebPortal.Controllers
{
    public class GroupController : Controller
    {
        private GroupsDBContext db = new GroupsDBContext();

        // GET: Group
        public ActionResult Index()
        {
            if (!Request.IsAuthenticated)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            List<int> arrayLinkCounts = new List<int>(),
                      arrayRedirectLinkCounts = new List<int>();

            int redirectLinkCount = 0, linkCount = 0;
            var groups = db.Groups;
            foreach (var group in groups)
            {
                redirectLinkCount = linkCount = 0;

                db.Links
                    .Where(link => link.GroupId == group.Id)
                    .ForEachAsync(link => { linkCount++; redirectLinkCount += link.RedirectedCount; })
                    .GetAwaiter()
                    .GetResult();

                arrayLinkCounts.Add(linkCount);
                arrayRedirectLinkCounts.Add(redirectLinkCount);
            }
            ViewBag.ArrayLinkCounts = arrayLinkCounts;
            ViewBag.ArrayRedirectLinkCounts = arrayRedirectLinkCounts;

            return View(db.Groups.Include(p => p.Links).Where(p => p.UserName == User.Identity.Name));
        }

        // GET: Group/Details/5
        public ActionResult Details(int? id)
        {
            if (!Request.IsAuthenticated)
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            GroupModel groupModel = db.Groups.Find(id);
            if (groupModel == null)
                return HttpNotFound();

            if (groupModel.UserName != User.Identity.Name)
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);

            return View(groupModel);
        }

        // GET: Group/Create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            return View();
        }

        // POST: Group/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] GroupModel groupModel)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (ModelState.IsValid)
            {
                groupModel.Status = true;
                groupModel.UserName = User.Identity.Name;
                db.Groups.Add(groupModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(groupModel);
        }

        // GET: Group/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            GroupModel groupModel = db.Groups.Find(id);
            if (groupModel.UserName != User.Identity.Name)
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);

            if (groupModel == null)
            {
                return HttpNotFound();
            }
            return View(groupModel);
        }

        // POST: Group/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] GroupModel groupModel)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (groupModel.UserName != User.Identity.Name)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (ModelState.IsValid)
            {
                db.Entry(groupModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(groupModel);
        }

        // GET: Group/Delete/5
        public ActionResult Delete(int? id)
        {
            GroupModel groupModel = db.Groups.Find(id);
            if ((!User.Identity.IsAuthenticated) && (groupModel.UserName != User.Identity.Name))
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (groupModel == null)
                return HttpNotFound();

            IQueryable<LinkModel> linksOnThisGroup = db.Links.Where(p => p.GroupId == id);
            db.Links.RemoveRange(linksOnThisGroup);
            db.Groups.Remove(groupModel);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult ChangeStatus(int? id)
        {
            GroupModel groupModel = db.Groups.Find(id);
            if ((!User.Identity.IsAuthenticated) && (groupModel.UserName != User.Identity.Name))
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            //Выключение группы
            bool newStatus = !db.Groups.Find(id).Status;
            db.Groups.Find(id).Status = newStatus;
            db.SaveChanges();

            //Выключение ссылок
            if (!newStatus)
            {
                var linksOnThisGroup = db.Links.Where(p => p.GroupId == id);
                foreach (LinkModel item in db.Links)
                {
                    item.Status = false;
                }
                db.SaveChanges();
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebPortal/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebPortal.Models;

namespace WebPortal.Controllers
{
    public class LinkController : Controller
    {
        private GroupsDBContext db = new GroupsDBContext();

        // GET: Link
        public ActionResult Index(int? id)
        {
            if (id == null)
                return View(db.Links.Where(link => link.UserName == User.Identity.Name).ToList());
            ViewBag.GroupId = id;
            ViewBag.GroupName = db.Groups.Find(id).Name;

            return View(db.Links.Where(p => p.GroupId == id).ToList());
        }

        // GET: Link/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinkModel linkModel = db.Links.Find(id);
            if (linkModel == null)
            {
                return HttpNotFound();
            }
            if (linkModel.UserName != User.Identity.Name)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            return View(linkModel);
        }

        // GET: Link/Create
        public ActionResult Create(int groupId)
        {
            ViewBag.GroupId = groupId;
            return View();
        }

        // POST: Link/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,LongLink,GroupId,Status")] LinkModel linkModel)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (ModelState.IsValid)
            {
                linkModel.RedirectedCount = 0;
                linkModel.ShortLink = "";
                linkModel.UserName = User.Identity.Name;
                linkModel.Status = true;

                db.Links.Add(linkModel);
                db.SaveChanges();

                string shortLink = $"{Request.Url.Scheme}://{Request.Url.Authority}{Request.ApplicationPath.TrimEnd('/')}/r/{linkModel.Id}";
                db.Links.Find(linkModel.Id).ShortLink = shortLink;
                db.SaveChanges();

                return RedirectToAction($"Index/{linkModel.GroupId}");
            }

            return View(linkModel);
        }

        // GET: Link/Edit/5
        public ActionResult Open(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinkModel linkModel = db.Links.Find(id);
            if (linkModel.UserName != User.Identity.Name)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (linkModel == null)
            {
                return HttpNotFound();
            }
            var link = db.Links.Find(id);
            link.RedirectedCount += 1;
            db.SaveChanges();
            return Redirect(link.LongLink);
        }

        // POST: Link/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LongLink,ShortLink,RedirectedCount,GroupId")] LinkModel linkModel)
        {
            if (ModelState.IsValid)
            {
                linkModel.UserName = User.Identity.Name;
                db.Entry(linkModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(linkModel);
        }

        // GET: Link/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinkModel linkModel = db.Links.Find(id);
            if (linkModel.UserName != User.Identity.Name)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            if (linkModel == null)
            {
                return HttpNotFound();
            }
            db.Links.Remove(linkModel);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult ChangeStatus(int id)
        {
            LinkModel linkModel = db.Links.Find(id);
            if (linkModel.UserName != User.Identity.Name)
                return RedirectToRoute(new
                {
                    controller = "Exceptions",
                    action = "Unauthorized"
                });

            db.Links.Find(id).Status = !db.Links.Find(id).Status;
            db.SaveChanges();

            return Redirect(Request.UrlReferrer.ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebPortal/Views/Link/Create.cshtml
@model WebPortal.Models.LinkModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>LinkModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, "Название", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LongLink, "Сокращаемая ссылка", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LongLink, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LongLink, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад к списку ссылок", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebPortal/Views/Link/Delete.cshtml
@model WebPortal.Models.LinkModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LinkModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RedirectedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedirectedCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebPortal/Views/Link/Details.cshtml
@model WebPortal.Models.LinkModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LinkModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Имя
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Длинная ссылка
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongLink)
        </dd>

        <dt>
            Короткая ссылка
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortLink)
        </dd>

        <dt>
            Редиректов:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedirectedCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад к списку ссылок", "Index")
</p>

WebPortal/Views/Link/Edit.cshtml
@model WebPortal.Models.LinkModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>LinkModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RedirectedCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RedirectedCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RedirectedCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebPortal/Views/Link/Index.cshtml
@model IEnumerable<WebPortal.Models.LinkModel>

@{
    ViewBag.Title = "Ссылки";
    if (ViewBag.GroupName != null)
    { <h2 class="btn-top">Ссылки группы @ViewBag.GroupName</h2>}
    else
    { <h2 class="btn-top">Все ссылки</h2> }
}


@{ 
    if (ViewBag.GroupName != null)
    {
    <p>
        <button type="button" class="btn btn-success">
            @Html.ActionLink("Создать новую ссылку", "Create", new { groupId = ViewBag.GroupId })
        </button>
    </p>
    }
}
<table class="table">
    <tr>
        <th>
            Статус:
        </th>
        <th>
            Название:
        </th>
        <th>
            Длинная ссылка:
        </th>
        <th>
            Короткая ссылка:
        </th>
        <th>
            Редиректов:
        </th>
        <th>Удалить:</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("ChangeStatus", "Link", new { id = item.Id })">
                    @{ if (item.Status)
                        {
                            <div class="toggleButton toggleButtonOn">
                                <span class="toogleButtonCaption">ON</span>
                                @Html.CheckBoxFor(p => item.Status, htmlAttributes: new { @class = "CheckBoxSel" })
                            </div>
                        }
                        else
                        {
                            <div class="toggleButton toggleButtonOff">
                                <span class="toogleButtonCaption">OFF</span>
                                @Html.CheckBoxFor(p => item.Status, htmlAttributes: new { @class = "CheckBoxSel" })
                            </div>
                        }
                    }
                </a>
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.LongLink
            </td>
            <td>
                @item.ShortLink
            </td>
            <td>
                @item.RedirectedCount
            </td>
            <td>
                <button type="button" class="btn btn-danger btn-close">
                    @Html.ActionLink("X", "Delete", new { id = item.Id })
                </button>
            </td>
        </tr>
    }

</table>


<div>
    @Html.ActionLink("Назад к списку групп", "Index", "Group")
</div>

WebPortal/Views/Link/View.cshtml
@model WebPortal.Models.LinkModel

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>LinkModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RedirectedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RedirectedCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>